export const apiUrl = import.meta.env.VITE_BACKEND_API_URL;

export const LOCAL_STORAGE_TOKEN_NAME = "accessToken";
export const LOCAL_STORAGE_USER = "userId";

export const SET_AUTH = "SET_AUTH";
export const UPDATE_AUTH = "UPDATE_AUTH";

export const SET_PROVINCES = "SET_PROVINCES";
export const SET_DISTRICTS = "SET_DISTRICTS";
export const SET_VILLAGES = "SET_VILLAGES";
export const SET_ADDRESSES = "SET_ADDRESSES";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const SET_SHOP_INFO = "SET_SHOP_INFO";
export const UPDATE_SHOP_INFO = "UPDATE_SHOP_INFO";
export const SET_ROLE = "SET_ROLE";
export const SET_AVATAR = "SET_AVATAR";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";

export const SET_AUTH_ADMIN = "SET_AUTH_ADMIN";

export const SET_ALL_CATEGORIES = "SET_ALL_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";

export const SET_ALL_SUB_CATEGORIES = "SET_ALL_SUB_CATEGORIES";
export const ADD_SUB_CATEGORY = "ADD_SUB_CATEGORY";
export const UPDATE_SUB_CATEGORY = "UPDATE_SUB_CATEGORY";
export const REMOVE_SUB_CATEGORY = "REMOVE_SUB_CATEGORY";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const SET_ALL_SUBCATEGORY_ATTRIBUTES = "SET_ALL_SUBCATEGORY_ATTRIBUTES";

export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS";

export const SET_ALL_CART = "SET_ALL_CART";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART ";

export const GET_VOUCHERS_SUCCESS = "GET_VOUCHERS_SUCCESS";
export const ADD_VOUCHER_SUCCESS = "ADD_VOUCHER_SUCCESS";
export const UPDATE_VOUCHER_SUCCESS = "UPDATE_VOUCHER_SUCCESS";
export const DELETE_VOUCHER_SUCCESS = "DELETE_VOUCHER_SUCCESS";

export const SET_VOUCHERS = "SET_VOUCHERS";
export const SET_SELECTED_VOUCHER = "SET_SELECTED_VOUCHER";
export const SET_LOADING = "SET_LOADING";

export const SET_ALL_ORDERS = "SET_ALL_ORDERS";
export const CANCLE_ORDER = "CANCLE_ORDER";
export const SET_ORDERS = "SET_ORDERS";
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";
export const SET_SHIPPING_PROVIDER = "SET_SHIPPING_PROVIDER";

export const SET_ERROR = "SET_ERROR";
